# Generated by Django 6.1 on 2026-08-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xaridapp', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Mijoz ismi')),
                ('status', models.CharField(default='New', max_length=50, verbose_name='Holati')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
        ),
    ]
