# Generated by Django 6.1 on 2026-08-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xaridapp', '0007_alter_order_options_order_user_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='manzil',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='mijoz_nomi',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='telefon_raqami',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='umumiy_narx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='yaratilgan_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='maqom',
            field=models.CharField(default='Kutilmoqda', max_length=50),
        ),
    ]
