# Generated by Django 6.1 on 2026-08-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xaridapp', '0008_alter_order_options_rename_address_order_manzil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-yaratilgan_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterField(
            model_name='order',
            name='manzil',
            field=models.TextField(verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='order',
            name='maqom',
            field=models.CharField(choices=[('Kutilmoqda', "⏳ To'lov kutilmoqda"), ("To'langan", "✅ To'langan"), ('Qabul qilindi', '📦 Qabul qilindi'), ('Yuborildi', '🚚 Yuborildi'), ('Yetkazildi', '🎉 Yetkazildi'), ('Bekor qilindi', '❌ Bekor qilindi')], default='Kutilmoqda', max_length=50, verbose_name='Buyurtma holati'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mijoz_nomi',
            field=models.CharField(max_length=100, verbose_name='Mijoz nomi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telefon_raqami',
            field=models.CharField(max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='order',
            name='umumiy_narx',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Umumiy narx'),
        ),
        migrations.AlterField(
            model_name='order',
            name='yaratilgan_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
    ]
