# Generated by Django 6.1 on 2026-08-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xaridapp', '0009_alter_order_options_alter_order_manzil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi")),
                ('tasdiqlangan', models.BooleanField(default=False, verbose_name="To'lov tasdiqlanganmi?")),
                ('yaratilgan_at', models.DateTimeField(auto_now_add=True, verbose_name="To'lov vaqti")),
                ('tasdiqlangan_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tolov', to='Xaridapp.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-yaratilgan_at'],
            },
        ),
    ]
